# Generated by Django 3.1.1 on 2020-12-01 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imagem', models.FileField(blank=True, null=True, upload_to='media/')),
                ('categoria', models.TextField(choices=[(0, 'Alto Padrão'), (1, 'Médio Padrão'), (2, 'Baixo Padrão')], default=0)),
                ('negocio', models.TextField(choices=[(0, 'Aluguel'), (1, 'Arrendamento'), (2, 'Venda')], default=0)),
                ('titulo', models.CharField(max_length=250, unique=True)),
                ('endereco', models.CharField(max_length=300, unique=True)),
                ('area', models.IntegerField(unique=True)),
                ('num_quarto', models.IntegerField(unique=True)),
                ('num_banheiro', models.IntegerField(unique=True)),
                ('num_vaga', models.IntegerField(unique=True)),
                ('descricao', models.TextField(unique=True)),
                ('status', models.TextField(choices=[(0, 'Disponível'), (1, 'Indisponível')], default=0)),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_imoveis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(null=True, upload_to='media/imoveis', verbose_name='Imagem')),
                ('imovel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Imagem_imoveis', to='system.imovel')),
            ],
            options={
                'verbose_name': 'Galeria do Imóvel',
                'verbose_name_plural': 'Galeria do Imóvel',
            },
        ),
        migrations.CreateModel(
            name='Corretor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cri', models.IntegerField(default=0)),
                ('telefone', models.CharField(max_length=250, unique=True)),
                ('endereco', models.CharField(max_length=300, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_corretores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Corretor',
                'verbose_name_plural': 'Corretores',
                'ordering': ['-pk'],
            },
        ),
    ]
