# Generated by Django 3.1.1 on 2020-10-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='descricao',
            field=models.TextField(unique=True),
        ),
    ]
