# Generated by Django 3.1.1 on 2020-10-07 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20201007_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(null=True, upload_to='media/imoveis', verbose_name='Imagem')),
                ('imovel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Imagem_imoveis', to='system.imovel')),
            ],
            options={
                'verbose_name': 'Galeria do Imóvel',
                'verbose_name_plural': 'Galeria do Imóvel',
            },
        ),
    ]
