# Generated by Django 3.1.1 on 2020-10-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_galeria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
