# Generated by Django 3.1.1 on 2020-10-11 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20201007_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corretor',
            options={'ordering': ['-nome'], 'verbose_name': 'Corretor', 'verbose_name_plural': 'Corretores'},
        ),
        migrations.AlterModelOptions(
            name='imovel',
            options={'ordering': ['-titulo'], 'verbose_name': 'Imóvel', 'verbose_name_plural': 'Imóveis'},
        ),
    ]
