# Generated by Django 3.1.1 on 2020-11-27 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20201011_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corretor',
            options={'ordering': ['-pk'], 'verbose_name': 'Corretor', 'verbose_name_plural': 'Corretores'},
        ),
    ]
